before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - id: binary
    main: ./cmd/ansible-operator/
    binary: ansible-operator
    asmflags: "{{ .Env.GO_BUILD_ASMFLAGS }}"
    gcflags: "{{ .Env.GO_BUILD_GCFLAGS }}"
    ldflags: "{{ .Env.GO_BUILD_LDFLAGS }}"
    mod_timestamp: "{{ .CommitTimestamp }}"
    no_unique_dist_dir: true
    goos:
    - linux
    goarch:
    - amd64
dockers:
- image_templates:
  - "{{ .Env.IMAGE_REPO }}:{{ .Env.IMAGE_TAG }}-amd64"
  dockerfile: images/ansible-operator/Dockerfile
  goos: linux
  goarch: amd64
  use: buildx
  build_flag_templates:
    - "--platform=linux/amd64"
  extra_files:
    - "images/ansible-operator/Pipfile"
    - "images/ansible-operator/Pipfile.lock"
archives:
  - format: binary
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
release:
  disable: true
