module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.22.0

toolchain go1.22.8

require sigs.k8s.io/controller-runtime/tools/setup-envtest v0.0.0-20241019152504-013f46fbca88
